# Generated by Django 5.0.7 on 2025-12-08 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0007_medicalreport_reportcomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('condition', 'Medical Condition'), ('medication', 'Medication'), ('allergy', 'Allergy'), ('surgery', 'Surgery/Procedure'), ('visit', 'Doctor Visit'), ('lab_result', 'Lab Result')], max_length=20)),
                ('source', models.CharField(choices=[('INTAKE', 'AI Intake Form'), ('OCR', 'OCR Report Analysis'), ('DOCTOR', 'Doctor Manual Entry'), ('MANUAL', 'Patient Manual Entry')], max_length=10)),
                ('title', models.CharField(help_text='Main title/name of the entry', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('historical', 'Historical'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='When it started/was diagnosed', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When it ended/was resolved', null=True)),
                ('recorded_date', models.DateField(auto_now_add=True)),
                ('source_reference_id', models.CharField(blank=True, help_text='ID of source record (intake form ID, report ID, etc.)', max_length=100)),
                ('source_reference_type', models.CharField(blank=True, help_text='Type of source (AIIntakeForm, MedicalReport, etc.)', max_length=50)),
                ('severity', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], max_length=20, null=True)),
                ('is_chronic', models.BooleanField(default=False)),
                ('requires_monitoring', models.BooleanField(default=False)),
                ('is_critical', models.BooleanField(default=False)),
                ('category_data', models.JSONField(blank=True, default=dict, help_text='Category-specific structured data')),
                ('verified_by_doctor', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Array of tags for filtering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_history_entries', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patient.patientprofile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history_entries', to='patient.doctorpatientworkspace')),
            ],
            options={
                'verbose_name': 'Medical History Entry',
                'verbose_name_plural': 'Medical History Entries',
                'ordering': ['-recorded_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistorySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_conditions', models.IntegerField(default=0)),
                ('active_conditions', models.IntegerField(default=0)),
                ('total_medications', models.IntegerField(default=0)),
                ('current_medications', models.IntegerField(default=0)),
                ('total_allergies', models.IntegerField(default=0)),
                ('total_surgeries', models.IntegerField(default=0)),
                ('total_visits', models.IntegerField(default=0)),
                ('total_lab_results', models.IntegerField(default=0)),
                ('has_chronic_conditions', models.BooleanField(default=False)),
                ('has_critical_allergies', models.BooleanField(default=False)),
                ('requires_monitoring', models.BooleanField(default=False)),
                ('last_visit_date', models.DateField(blank=True, null=True)),
                ('active_conditions_list', models.JSONField(blank=True, default=list)),
                ('current_medications_list', models.JSONField(blank=True, default=list)),
                ('all_allergies_list', models.JSONField(blank=True, default=list)),
                ('recent_labs_list', models.JSONField(blank=True, default=list)),
                ('completeness_score', models.IntegerField(default=0, help_text='Percentage of expected history fields filled (0-100)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history_summary', to='patient.patientprofile')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history_summary', to='patient.doctorpatientworkspace')),
            ],
            options={
                'verbose_name': 'Medical History Summary',
                'verbose_name_plural': 'Medical History Summaries',
            },
        ),
        migrations.CreateModel(
            name='MedicalHistoryTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('added', 'Entry Added'), ('updated', 'Entry Updated'), ('verified', 'Verified by Doctor'), ('resolved', 'Marked as Resolved'), ('flagged', 'Flagged for Review')], max_length=20)),
                ('event_description', models.TextField()),
                ('event_data', models.JSONField(blank=True, default=dict, help_text='Additional event metadata')),
                ('performed_by_type', models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('system', 'System')], default='system', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('history_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='patientHistory.medicalhistoryentry')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_timeline_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical History Timeline Event',
                'verbose_name_plural': 'Medical History Timeline Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='medicalhistoryentry',
            index=models.Index(fields=['patient', 'category'], name='patientHist_patient_9ac667_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalhistoryentry',
            index=models.Index(fields=['workspace', 'category'], name='patientHist_workspa_e80af4_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalhistoryentry',
            index=models.Index(fields=['source'], name='patientHist_source_78bd96_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalhistoryentry',
            index=models.Index(fields=['status'], name='patientHist_status_563d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalhistoryentry',
            index=models.Index(fields=['-recorded_date'], name='patientHist_recorde_9daae1_idx'),
        ),
    ]
