# Generated by Django 5.0.7 on 2025-12-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientHistory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistoryentry',
            name='recorded_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
