# Generated by Django 5.0.7 on 2025-12-08 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_medicalreport_reportcomment_and_more'),
        ('patientHistory', '0002_alter_medicalhistoryentry_recorded_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistoryentry',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='AI-generated insights for this specific entry'),
        ),
        migrations.AddField(
            model_name='medicalhistoryentry',
            name='last_value',
            field=models.CharField(blank=True, help_text='Most recent value (for lab results/vitals)', max_length=100),
        ),
        migrations.AddField(
            model_name='medicalhistoryentry',
            name='trending_direction',
            field=models.CharField(blank=True, choices=[('improving', 'Improving'), ('worsening', 'Worsening'), ('stable', 'Stable'), ('unknown', 'Unknown')], default='unknown', help_text='Trend analysis for trackable parameters', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalhistorysummary',
            name='ai_clinical_summary',
            field=models.TextField(blank=True, help_text='Groq AI-generated comprehensive clinical summary'),
        ),
        migrations.AddField(
            model_name='medicalhistorysummary',
            name='ai_focus_points',
            field=models.JSONField(blank=True, default=list, help_text='AI-suggested focus points for doctor attention'),
        ),
        migrations.AddField(
            model_name='medicalhistorysummary',
            name='ai_last_generated',
            field=models.DateTimeField(blank=True, help_text='When AI summary was last generated', null=True),
        ),
        migrations.AddField(
            model_name='medicalhistorysummary',
            name='ai_risk_assessment',
            field=models.JSONField(blank=True, default=dict, help_text='AI-identified risk factors with severity levels'),
        ),
        migrations.AddField(
            model_name='medicalhistorysummary',
            name='ai_trends_detected',
            field=models.JSONField(blank=True, default=list, help_text='List of trends detected by AI (improving/worsening parameters)'),
        ),
        migrations.AddField(
            model_name='medicalhistorysummary',
            name='critical_alerts_count',
            field=models.IntegerField(default=0, help_text='Count of critical items requiring attention'),
        ),
        migrations.AddField(
            model_name='medicalhistorysummary',
            name='unverified_entries_count',
            field=models.IntegerField(default=0, help_text='Count of entries not yet verified by doctor'),
        ),
        migrations.CreateModel(
            name='ClinicalTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(choices=[('lab_value', 'Lab Value'), ('vital_sign', 'Vital Sign'), ('symptom_severity', 'Symptom Severity'), ('medication_response', 'Medication Response')], help_text='Type of parameter being tracked', max_length=50)),
                ('parameter_name', models.CharField(help_text='Name of parameter (e.g., HbA1c, Blood Pressure, Glucose)', max_length=100)),
                ('parameter_unit', models.CharField(blank=True, help_text='Unit of measurement (e.g., %, mg/dL, mmHg)', max_length=20)),
                ('data_points', models.JSONField(default=list, help_text='Array of {date, value, is_abnormal, source} objects')),
                ('reference_range_min', models.FloatField(blank=True, null=True)),
                ('reference_range_max', models.FloatField(blank=True, null=True)),
                ('reference_range_text', models.CharField(blank=True, help_text='Text representation of reference range', max_length=100)),
                ('trend_direction', models.CharField(choices=[('improving', 'Improving'), ('worsening', 'Worsening'), ('stable', 'Stable'), ('fluctuating', 'Fluctuating'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('latest_value', models.CharField(blank=True, max_length=100)),
                ('latest_value_date', models.DateField(blank=True, null=True)),
                ('is_currently_abnormal', models.BooleanField(default=False)),
                ('ai_interpretation', models.TextField(blank=True, help_text='AI-generated interpretation of the trend')),
                ('clinical_significance', models.TextField(blank=True, help_text='Clinical significance of this trend')),
                ('last_analyzed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_trends', to='patient.patientprofile')),
                ('related_entries', models.ManyToManyField(blank=True, related_name='trends', to='patientHistory.medicalhistoryentry')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_trends', to='patient.doctorpatientworkspace')),
            ],
            options={
                'verbose_name': 'Clinical Trend',
                'verbose_name_plural': 'Clinical Trends',
                'ordering': ['-last_analyzed'],
                'indexes': [models.Index(fields=['workspace', 'parameter_name'], name='patientHist_workspa_58d78e_idx'), models.Index(fields=['patient', 'trend_type'], name='patientHist_patient_0bf665_idx')],
                'unique_together': {('workspace', 'parameter_name')},
            },
        ),
    ]
