# Generated by Django 5.0.7 on 2025-12-02 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctorprofile_options_doctorprofile_city_and_more'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Patient Profile', 'verbose_name_plural': 'Patient Profiles'},
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='chronic_conditions',
            field=models.TextField(blank=True, help_text='Comma-separated list of chronic conditions'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='current_medications',
            field=models.TextField(blank=True, help_text='Current medications'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='current_step',
            field=models.IntegerField(default=0, help_text='Current step in profile setup (0-3)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='known_allergies',
            field=models.TextField(blank=True, help_text='Comma-separated list of allergies'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='note_for_doctors',
            field=models.CharField(blank=True, help_text='What should your doctor know first?', max_length=140),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='patient_id',
            field=models.CharField(blank=True, editable=False, help_text='Format: PT-YYYY-XXXXX', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='preferred_contact_method',
            field=models.CharField(choices=[('phone', 'Phone'), ('sms', 'SMS'), ('email', 'Email'), ('app_notification', 'App Notification')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='prescription_upload',
            field=models.FileField(blank=True, help_text='Upload prescription (max 10MB)', null=True, upload_to='patient_prescriptions/'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='share_data_for_research',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PatientDoctorConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('removed', 'Removed')], default='pending', max_length=20)),
                ('initiated_by', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor')], default='patient', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('patient_note', models.TextField(blank=True, help_text="Patient's note when requesting connection")),
                ('doctor_note', models.TextField(blank=True, help_text="Doctor's note when accepting/rejecting")),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_connections', to='doctor.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_connections', to='patient.patientprofile')),
            ],
            options={
                'verbose_name': 'Patient-Doctor Connection',
                'verbose_name_plural': 'Patient-Doctor Connections',
                'ordering': ['-created_at'],
                'unique_together': {('patient', 'doctor')},
            },
        ),
    ]
