# Generated by Django 5.0.7 on 2025-12-02 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctorprofile_options_doctorprofile_city_and_more'),
        ('patient', '0002_alter_patientprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdoctorconnection',
            name='connection_type',
            field=models.CharField(choices=[('request', 'Connection Request'), ('qr_code', 'QR Code Scan')], default='request', help_text='How the connection was initiated', max_length=20),
        ),
        migrations.CreateModel(
            name='ConnectionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiration timestamp')),
                ('is_used', models.BooleanField(default=False, help_text='Whether token has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When token was used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_uses', models.IntegerField(default=1, help_text='Maximum number of times token can be used')),
                ('use_count', models.IntegerField(default=0, help_text='Number of times token has been used')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_tokens', to='doctor.doctorprofile')),
                ('used_by_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_tokens', to='patient.patientprofile')),
            ],
            options={
                'verbose_name': 'Connection Token',
                'verbose_name_plural': 'Connection Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='patientdoctorconnection',
            name='qr_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connections', to='patient.connectiontoken'),
        ),
    ]
