# Generated by Django 5.0.7 on 2025-12-03 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctorprofile_options_doctorprofile_city_and_more'),
        ('patient', '0003_patientdoctorconnection_connection_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPatientWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Care Journey', max_length=150)),
                ('summary', models.TextField(blank=True)),
                ('primary_diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('medication_overview', models.TextField(blank=True)),
                ('lifestyle_guidelines', models.TextField(blank=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to='patient.patientdoctorconnection')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_workspaces', to='doctor.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_workspaces', to='patient.patientprofile')),
            ],
            options={
                'verbose_name': 'Doctor Patient Workspace',
                'verbose_name_plural': 'Doctor Patient Workspaces',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorPatientTimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('update', 'General Update'), ('treatment', 'Treatment Plan'), ('medication', 'Medication'), ('diagnostic', 'Diagnostic/Test'), ('guideline', 'Guideline'), ('appointment', 'Appointment'), ('alert', 'Alert')], default='update', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('follow_up_actions', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('patient', 'Shared with Patient'), ('internal', 'Internal Note')], default='patient', max_length=20)),
                ('created_by', models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('system', 'System')], default='doctor', max_length=20)),
                ('is_critical', models.BooleanField(default=False)),
                ('highlight_color', models.CharField(blank=True, max_length=20)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='patient.doctorpatientworkspace')),
            ],
            options={
                'verbose_name': 'Doctor Patient Timeline Entry',
                'verbose_name_plural': 'Doctor Patient Timeline Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
