# Generated by Django 5.0.7 on 2025-12-05 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctorprofile_options_doctorprofile_city_and_more'),
        ('patient', '0004_doctorpatientworkspace_doctorpatienttimelineentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIIntakeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Patient Intake Form', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this form is for')),
                ('doctor_prompt', models.TextField(help_text="Doctor's input prompt for AI generation")),
                ('ai_raw_response', models.TextField(blank=True, help_text='Raw AI response for debugging')),
                ('form_schema', models.JSONField(default=dict, help_text='Structured form fields with type, label, required, options, etc.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Patient'), ('in_progress', 'Patient is Filling'), ('submitted', 'Submitted by Patient'), ('reviewed', 'Reviewed by Doctor')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated summary of patient responses')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_intake_forms', to='doctor.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_intake_forms', to='patient.patientprofile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_forms', to='patient.doctorpatientworkspace')),
            ],
            options={
                'verbose_name': 'AI Intake Form',
                'verbose_name_plural': 'AI Intake Forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntakeFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_data', models.JSONField(default=dict, help_text="Patient's answers to all form fields")),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='patient.aiintakeform')),
            ],
            options={
                'verbose_name': 'Intake Form Response',
                'verbose_name_plural': 'Intake Form Responses',
            },
        ),
        migrations.CreateModel(
            name='IntakeFormUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(help_text='ID of the file upload field in form schema', max_length=100)),
                ('field_label', models.CharField(help_text='Label of the upload field', max_length=255)),
                ('file', models.FileField(upload_to='intake_form_uploads/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('upload_type', models.CharField(choices=[('medical_report', 'Medical Report'), ('lab_result', 'Lab Result'), ('prescription', 'Prescription'), ('imaging', 'Imaging/Scan'), ('document', 'Document'), ('other', 'Other')], default='document', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='patient.aiintakeform')),
            ],
            options={
                'verbose_name': 'Intake Form Upload',
                'verbose_name_plural': 'Intake Form Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
