# Generated by Django 5.0.7 on 2025-12-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_aiintakeform_intakeformresponse_intakeformupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiintakeform',
            name='ai_analysis',
            field=models.JSONField(blank=True, help_text='Detailed AI analysis: insights, urgency, key findings, symptoms, conditions', null=True),
        ),
        migrations.AddField(
            model_name='aiintakeform',
            name='ocr_processed',
            field=models.BooleanField(default=False, help_text='Whether OCR has been run on uploaded documents'),
        ),
        migrations.AddField(
            model_name='aiintakeform',
            name='ocr_results',
            field=models.JSONField(blank=True, help_text='Aggregated OCR results from all uploaded documents', null=True),
        ),
        migrations.AddField(
            model_name='intakeformupload',
            name='ocr_confidence',
            field=models.FloatField(default=0.0, help_text='OCR confidence score (0-1)'),
        ),
        migrations.AddField(
            model_name='intakeformupload',
            name='ocr_medical_data',
            field=models.JSONField(blank=True, help_text='Structured medical information extracted via OCR (medications, diagnoses, test results, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='intakeformupload',
            name='ocr_processed',
            field=models.BooleanField(default=False, help_text='Whether OCR has been run on this file'),
        ),
        migrations.AddField(
            model_name='intakeformupload',
            name='ocr_text',
            field=models.TextField(blank=True, help_text='Extracted text from OCR processing'),
        ),
    ]
