# Generated by Django 5.0.7 on 2025-12-07 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_aiintakeform_ai_analysis_aiintakeform_ocr_processed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('lab_report', 'Lab Report'), ('xray', 'X-Ray'), ('mri', 'MRI'), ('ct_scan', 'CT Scan'), ('ultrasound', 'Ultrasound'), ('prescription', 'Prescription'), ('discharge_summary', 'Discharge Summary'), ('consultation', 'Consultation Notes'), ('vaccination', 'Vaccination Record'), ('blood_test', 'Blood Test'), ('pathology', 'Pathology Report'), ('radiology', 'Radiology Report'), ('other', 'Other Medical Document')], default='other', max_length=50)),
                ('title', models.CharField(help_text='Brief title for the report', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Patient notes about this report')),
                ('report_date', models.DateField(help_text='Date of the actual report/test')),
                ('file', models.FileField(help_text='Upload medical report (PDF, Image, or Document)', upload_to='medical_reports/%Y/%m/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing OCR'), ('ocr_complete', 'OCR Complete'), ('ai_analyzing', 'AI Analyzing'), ('ready_for_review', 'Ready for Doctor Review'), ('reviewed', 'Reviewed by Doctor')], default='uploaded', max_length=30)),
                ('ocr_processed', models.BooleanField(default=False)),
                ('ocr_text', models.TextField(blank=True, help_text='Raw text extracted from document')),
                ('ocr_confidence', models.FloatField(default=0.0, help_text='OCR confidence score (0-1)')),
                ('ocr_processed_at', models.DateTimeField(blank=True, null=True)),
                ('extracted_medications', models.JSONField(blank=True, help_text='List of medications extracted from report', null=True)),
                ('extracted_diagnoses', models.JSONField(blank=True, help_text='List of diagnoses/conditions extracted', null=True)),
                ('extracted_vitals', models.JSONField(blank=True, help_text='Vital signs extracted (BP, HR, temp, etc.)', null=True)),
                ('extracted_test_results', models.JSONField(blank=True, help_text='Lab test results with values and ranges', null=True)),
                ('extracted_allergies', models.JSONField(blank=True, help_text='Allergies mentioned in the report', null=True)),
                ('ai_processed', models.BooleanField(default=False)),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated summary of the report')),
                ('ai_key_findings', models.JSONField(blank=True, help_text='Key findings identified by AI', null=True)),
                ('ai_recommendations', models.TextField(blank=True, help_text='AI recommendations for doctor')),
                ('ai_processed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_raw_response', models.JSONField(blank=True, help_text='Full raw response from AI analysis', null=True)),
                ('reviewed_by_doctor', models.BooleanField(default=False)),
                ('doctor_notes', models.TextField(blank=True, help_text="Doctor's notes about this report")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_critical', models.BooleanField(default=False, help_text='Mark if report contains critical findings')),
                ('requires_action', models.BooleanField(default=False, help_text='Mark if report requires immediate action')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='patient.patientprofile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='patient.doctorpatientworkspace')),
            ],
            options={
                'verbose_name': 'Medical Report',
                'verbose_name_plural': 'Medical Reports',
                'ordering': ['-report_date', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor')], max_length=10)),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal doctor notes (not visible to patient)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_comments', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='patient.medicalreport')),
            ],
            options={
                'verbose_name': 'Report Comment',
                'verbose_name_plural': 'Report Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='medicalreport',
            index=models.Index(fields=['patient', '-report_date'], name='patient_med_patient_45af1d_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreport',
            index=models.Index(fields=['workspace', '-uploaded_at'], name='patient_med_workspa_e0d298_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreport',
            index=models.Index(fields=['status'], name='patient_med_status_2605fd_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreport',
            index=models.Index(fields=['report_type'], name='patient_med_report__ace467_idx'),
        ),
    ]
