# Generated by Django 5.0.7 on 2025-12-01 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Doctor Profile', 'verbose_name_plural': 'Doctor Profiles'},
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_mode',
            field=models.CharField(blank=True, choices=[('teleconsultation', 'Teleconsultation'), ('in_person', 'In-Person'), ('both', 'Both')], max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='current_step',
            field=models.IntegerField(default=0, help_text='Current step in profile setup (0-4)'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text='e.g., Dr. John Smith', max_length=150),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_id',
            field=models.CharField(blank=True, editable=False, help_text='Format: DR-YYYY-XXXXX', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='doctor_licenses/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='primary_clinic_hospital',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='professional_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if status is rejected'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When profile was submitted for verification', null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short professional bio (max 280 characters)', max_length=280),
        ),
    ]
